# docker-compose.yaml
version: '3.7'

networks:
  db_network:
    driver: bridge

services:
  minio:
    image: bitnami/minio:latest
    container_name: minio
    ports:
      - "19000:9000"
      - "19001:9001"
    networks:
      - db_network
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopass
      MINIO_SKIP_CLIENT: "yes" # ERROR Unable to initialize console server: Specified port is already in use
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  minio-storage:
    driver: local