minio:
  login: ${MINIO_LOGIN:miniologin}
  password: ${MINIO_PASSWORD:miniopassword}
  host: ${MINIO_HOST:localhost}
  port: ${MINIO_PORT:19000}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true